### ISSUE TITLE
october-devをビルドできるようにする

### ISSUE THREAD

**Issue by arowM** [elm-jp/guide#226]
ヒント:
https://github.com/elm-jp/guide/pull/170#issuecomment-547161751

**Comment by negiboudu** [comment]
#194
も関係あったりしますか…？

**Comment by arowM** [comment]
関係ありますね！
ありがとうございます🌻

**Comment by negiboudu** [comment]
本件と関係があるかはわかりませんが、新しいMacを買ったのでビルドする環境を作り直したところ、エラーが発生してビルドできませんでした。
```
TypeError: cb.apply is not a function
    at /Users/suzukikatsuaki/guide/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:184:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! guide@1.0.0 install-gitbook: `replace --silent ',"elm-repl"' '' book.json && gitbook install && replace --silent '"youtube"' '"youtube","elm-repl"' book.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the guide@1.0.0 install-gitbook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suzukikatsuaki/.npm/_logs/2020-12-09T17_51_52_791Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! guide@1.0.0 postinstall: `npm run install-gitbook && npm run install-repl`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the guide@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suzukikatsuaki/.npm/_logs/2020-12-09T17_51_52_860Z-debug.log
```

node.jsのバージョンが関係あるかもしれないので、node.jsのバージョンを少し落としてみます。
https://teratail.com/questions/279576

**Comment by negiboudu** [comment]
ビルドできました！
結局Node.jsのバージョンを落としただけでうまくいきました。

### ビルド成功したときのバージョン
```
~ % node -v
v10.23.0
~ % npm -v 
6.14.8
```

すべてのバージョンを試したわけではありませんが、おそらくNode.jsのv12以降を使うとエラーになるのだろうと思われます。

**Comment by arowM** [comment]
僕の環境だとnode v13.6.0 でそのままビルドできちゃっているので、なにか環境との組み合わせもありそうですね！

とはいえ、nodeのバージョンを全員であわせたほうが無難なので、`package.json`の`dependencies`に`node`を入れちゃうハックをしたプルリクを作成しました。
https://github.com/elm-jp/guide/pull/237

これなら、グローバルインストールされた`node`のバージョンに関わらずビルドできるようになるんじゃないかなって思います！
もしお試しいただくなら、`node_modules`を削除した上で`npm i`から試していただく必要があります🌸
